KWS = {
  "typeof" => ->(x : String, y : Int32) { _typeof_(x,y) }, 
  "print" => ->(x : String, y : Int32) { puts x; return "",0 },
  "eval" => ->(x : String, y : Int32) { eval x; return "",0 },
  "ceval" => ->(x : String, y : Int32) { ceval x; return "",0 },
  "after" => ->(x : String, y : Int32) { _after_(x, y); return "",0 },
  "+" => ->(x : String, y : Int32) { r = plus(x, y); return "",r },
  "-" => ->(x : String, y : Int32) { r = minus(x, y); return "",r },
  "inc" => ->(x : String, y : Int32) { r = inc(x, y); return "",r },
  "dec"=> ->(x : String, y : Int32) { r = dec(x, y); return "",r },
  "<" => ->(x : String, y : Int32) { r = _lower_(x, y); return "",r },
  ">" => ->(x : String, y : Int32) { r =_higher_(x, y); return "",r },
  "if" => ->(x : String, y : Int32) { r = Code._if_(x, y); return "",r },
  "while" => ->(x : String, y : Int32) { r = Code._while_(x, y); return "",r },
  "end" => ->(x : String, y : Int32) { Code._end_; return "",0 },
  "every" => ->(x : String, y : Int32) { t = Timer.new; t.timer_test(x,y); return "",0 },
  "ls" => ->(x : String, y : Int32) { ls(x,y); return "",0 },
  "let" => ->(x : String, y : Int32) { let(x,y); return "",0 },
  "delete" => ->(x : String, y : Int32) { delete x; return "",0 },
  "clear" => ->(x : String, y : Int32) { clear x; return "",0 },
  "p" => ->(x : String, y : Int32) { _p_ x; return "",0 },
  "!" => ->(x : String, y : Int32) { system(x); return "",0 },
  "now" => ->(x : String, y : Int32) { puts Time.local.to_s("%H:%M:%S.%6N"); return "",0 },
  "date" => ->(x : String, y : Int32) { puts Time.local.to_s("%Y-%m-%d"); return "",0 },
  "test" => ->(x : String, y : Int32) { procloop; return "",0 },
  "sleep" => ->(x : String, y : Int32) { sleep(x.to_i); return "",0 },
  "pass" => ->(x : String, y : Int32) { pass; return "",0 },
  "cls" => ->(x : String, y : Int32) { print "\33c\e[3J"; return "",0 },
  "load" => ->(x : String, y : Int32) { Code.load x; return "",0 },
  "run" =>  ->(x : String, y : Int32) { Code.run (x); return "",0 },
  "split_run" => ->(x : String, y : Int32) { Code.split_run; return "",0 },
  "list" => ->(x : String, y : Int32) { Code.list; return "",0 },
  "help" => ->(x : String, y : Int32) { help(x); return "",0 },
  "debug" => ->(x : String, y : Int32) { VARS["debug"] = !VARS["debug"]; puts "debug is now: ", VARS["debug"]; return "",0 },
  "singlestep" => ->(x : String, y : Int32) { VARS["singlestep"] = !VARS["singlestep"]; puts "singlestep is now: ", VARS["singlestep"]; return "",0 },
  "exit" => ->(x : String, y : Int32) { exit(0); return "",0 },
}